server:
  port: 12356
spring:
  application:
    name: shatding-springboot-mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
sharding:
  jdbc:
    datasource:
      names: ds0
      # 数据源ds0
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://172.16.4.10:3306/shard
        username: root
        password: 310012
    config:
      sharding:
        props:
          sql.show: true
        tables:
          t_user:  #t_user表
            key-generator-column-name: id  #主键
            actual-data-nodes: ds0.t_user${0..4}    #数据节点,均匀分布
            table-strategy:  #分表策略
              inline: #行表达式
                sharding-column: city_id
                algorithm-expression: t_user${city_id % 5}  #按模运算分配